<a href="https://colab.research.google.com/github/Naralahari/dwm-/blob/main/clssification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB

from sklearn.model_selection import train_test_split
from sklearn import metrics

In [5]:
data=pd.read_csv("/content/Iris.csv")
data.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [6]:
X=data[["SepalLengthCm","SepalWidthCm","PetalLengthCm","PetalWidthCm"]].values

In [7]:
y=data["Species"]

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

In [10]:
model_DT = DecisionTreeClassifier()
model_DT = model_DT.fit(X_train,y_train)
y_predict_DT = model_DT.predict(X_test)

In [11]:
Actual_predicted_DT=pd.DataFrame({'predicted':y_predict_DT, 'Actual':y_test})
Actual_predicted_DT.head()

           predicted           Actual
87   Iris-versicolor  Iris-versicolor
111   Iris-virginica   Iris-virginica
10       Iris-setosa      Iris-setosa
91   Iris-versicolor  Iris-versicolor
49       Iris-setosa      Iris-setosa